name: cryptohub
description: Acompanhe criptomoedas, uma carteira virtual e notícias em português.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
          weight: 400
        - asset: assets/fonts/Manrope.ttf
          weight: 500
        - asset: assets/fonts/Manrope.ttf
          weight: 600
        - asset: assets/fonts/Manrope.ttf
          weight: 700
        - asset: assets/fonts/Manrope.ttf
          weight: 800
